apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: mechkeybr.com
  dnsNames:
    - mechkeybr.com
    - www.mechkeybr.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - mechkeybr.com
          - www.mechkeybr.com
