#KHD additional part (26.04.2020)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hrdata-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
